### ISSUE TITLE
"label can only be part of a statement" error

### ISSUE THREAD

**Issue by mooseman** [levirak/tabulate#1]
Hi -  I've just found tabulate - it sounds awesome!  
Unfortunately, I got the following error when running "make all" -  

  CC    build/main.o
src/main.c: In function ‘PrintDocument’:
src/main.c:2296:17: error: a label can only be part of a statement and a declaration is not a statement
 2296 |                 struct cell *TopCell = GetCell(Doc, Col, 0);
      |                 ^~~~~~
make: *** [Makefile:47: build/main.o] Error 1  

I'm running Linux Mint.  gcc version 9.4.0  ( Ubuntu 9.4.0-1ubuntu1~20.04.1 ).  I'm very happy to help with bugfixes, either this one or any others!  Keep up the great work!  
- mooseman

**Comment by levirak** [comment]
Thanks for stopping by. Though I wonder how you found this project at all.

It looks like the problem is that strict C doesn't permit a variable declaration to follow a label, even a switch case. In hindsight I knew this, but GCC 12 accepted it without complaint. Clang still chokes on it. I've pushed a change that should let you build the project.

As a side note, I'm noticing that I never published any example sheets for this program. As I recall the problem is that nearly all the sheets I write for this program contain my finances, which I'd rather not put on GitHub. Instead, here's  a sheet I wrote while filling a character's inventory for a Pathfinder 1e game. Just save this as a text file then pass it as the argument. e.g. `tabulate items.txt`

[items.txt](https://github.com/levirak/tabulate/files/10879367/items.txt)
```
Price	Weight	Count	Cost	Weight	Item
#:fmt 6.2	6.3	6.0	6.2	6.3	45

5.00	=1/2	1	=!Cost	=!Wght	Dagger (1d3)
35.00	=4/2	1	=!Cost	=!Wght	Crossbow, light (1d6)
0.10	0.1	20	=!Cost	=!Wght	Crossbow bolts
3.00	=1/2	1	=!Cost	=!Wght	Haramaki (not proficient)
#
5.00	=3/4	1	(free)	=!Wght	Outfit, Pickpocket's
1.00	?	2	=!Cost	?	Jewelry
#
2.00	=2/4	1	=!Cost	=!Wght	Backpack (1/2 cb.ft.)
0.10	=5/4	1	=!Cost	=!Wght	Bedroll
1.00	=0.5/4	1	=!Cost	=!Wght	Pouch, Belt (1/20 cb.ft. or 2.5 lb)
1.00	0	1	=!Cost	=!Wght	Flint and steal
8.00	0	1	=!Cost	=!Wght	Ink (1 oz.)
0.10	0	1	=!Cost	=!Wght	Inkpen
0.20	0	10	=!Cost	=!Wght	Parchment sheet
#0.80	4	1	=!Cost	=!Wght	Pot, iron (1 gal)
0.20	1	1	=!Cost	=!Wght	Kit, mess
0.01	0.5	1	=!Cost	=!Wght	Soap
5.00	2	1	=!Cost	=!Wght	Pouch, spell components
#0.01	1	10	=!Cost	=!Wght	Torch
0.50	=1/4	5	=!Cost	=!Wght	Rations, trail
1.00	=4/4	1	=!Cost	=!Wght	Waterskin (1/8 gal)
#
0.10	0	1	=!Cost	=!Wght	Dice
0.10	1	1	=!Cost	=!Wght	Cards (simple)
0.10	0	1	=!Cost	=!Wght	Dominoes (bone)

			=sum br	=sum br
#:summary D@
			=80-@^	=17-@^
#:define Cost A@*C@
#:define Wght B@*C@
# vim: noet ts=10 sw=10 tw=0
```

**Comment by mooseman** [comment]
Hi levirak -  great to hear from you!

  I'm a big fan of "public domain" software (and a big "thank you" for
putting tabulate under the Unlicense!).
I do searches of "Unlicense" software from time to time - that would be how
I found "tabulate".  :)

Many thanks for doing the fix!  I'll grab the latest code, have another go
at the build and will let you know how it goes!
Cheers - keep up the great work!

Andy

**Comment by mooseman** [comment]
Hi again levirak!  
  Great news -  I got the latest code with your fix and the build now works *perfectly!*  
Good stuff!  Many thanks for the fix and keep up the great work!  
- mooseman
